/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react'
import { useGLTF,Text } from '@react-three/drei'
import { RigidBody } from '@react-three/rapier'
import * as THREE from "three"


export function GasStation(props) {
  const { nodes, materials } = useGLTF('/GasStation.glb')
  return (
  <>
   <group scale={8} position={[-140,0,-30]} rotation-y={11} {...props} dispose={null}>
    <RigidBody type='fixed'>
   <group scale={6.146}>
      
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Plane_2.geometry}
          material={materials['Material.045']}
        />
      </group>

      <group position={[-3.141, 0.184, -6.98]} rotation={[0.804, 0, 0]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube019.geometry}
          material={materials['Material.008']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube019_1.geometry}
          material={materials['Material.009']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube019_2.geometry}
          material={materials['Material.015']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube019_3.geometry}
          material={materials['Material.039']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube019_4.geometry}
          material={materials['Material.040']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube019_5.geometry}
          material={materials['Material.038']}
        />
      </group>
      <group position={[-1.842, 0.907, -4.019]} scale={[0.717, 0.925, 0.925]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube020.geometry}
          material={materials['Material.001']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube020_1.geometry}
          material={materials['Material.002']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube020_2.geometry}
          material={materials['Material.003']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube020_3.geometry}
          material={materials['Material.003']}
        />
      </group>
    
      </RigidBody>
     
      <RigidBody type="fixed">
      <group position={[-4.572, 0.99, -4.051]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube021.geometry}
          material={materials['Material.004']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube021_1.geometry}
          material={materials['Material.005']}
        />
      </group>
      </RigidBody>
    
     <RigidBody type='fixed'>
     <group position={[4.829, 4.603, 2.389]} rotation={[Math.PI / 2, 0, Math.PI]} scale={0.825}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Text003.geometry}
          material={materials['Material.013']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Text003_1.geometry}
          material={materials['Material.019']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Text003_2.geometry}
          material={materials['Material.015']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Text003_3.geometry}
          material={materials['Material.027']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Text003_4.geometry}
          material={materials['Material.026']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Text003_5.geometry}
          material={materials['Material.018']}
        />
      </group>

      <group position={[-3.465, 6.765, -2.254]} rotation={[Math.PI / 2, 0, Math.PI]} scale={1.137}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Text004.geometry}
          material={materials['Material.016']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Text004_1.geometry}
          material={materials['Material.022']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Text004_2.geometry}
          material={materials['Material.023']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Text004_3.geometry}
          material={materials['Material.024']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Text004_4.geometry}
          material={materials['Material.025']}
        />
      </group>
     </RigidBody>
 
      <RigidBody type='fixed'>
      <group
        position={[5.927, 0.065, -7.475]}
        rotation={[0, 0.524, 0]}
        scale={[0.171, 0.087, 0.171]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cylinder015.geometry}
          material={materials['Material.041']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cylinder015_1.geometry}
          material={materials['Material.042']}
        />
      </group>
</RigidBody>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.electricity_pole.geometry}
        material={materials['Material.043']}
        position={[-6.593, 9.128, 6.131]}
        scale={[0.135, 0.083, 1.709]}
      />
       <RigidBody type='fixed'>
       <group position={[-3.659, 5.216, 2.986]} rotation={[-Math.PI / 2, 0, 0]} scale={0.158}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cylinder003.geometry}
          material={materials['Material.010']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cylinder003_1.geometry}
          material={materials['Material.012']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cylinder003_2.geometry}
          material={materials['Material.013']}
        />
      </group>
</RigidBody>
      <group position={[-3.659, 5.216, 2.986]} rotation={[-Math.PI / 2, 0, 0]} scale={0.158}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cylinder003.geometry}
          material={materials['Material.010']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cylinder003_1.geometry}
          material={materials['Material.012']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cylinder003_2.geometry}
          material={materials['Material.013']}
        />
      </group>
   
  <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube022.geometry}
        material={materials['Material.014']}
      />

<RigidBody type='fixed'>


      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube022_1.geometry}
        material={materials['Material.017']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube022_2.geometry}
        material={materials['Material.029']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube022_3.geometry}
        material={materials['Material.030']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube022_4.geometry}
        material={materials['Material.031']}
      />
       </RigidBody>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube022_5.geometry}
        material={materials['Material.032']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube022_6.geometry}
        material={materials['Material.033']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube022_7.geometry}
        material={materials['Material.034']}
      />
      <RigidBody type='fixed'>

      
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube022_8.geometry}
        material={materials['Material.035']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube022_9.geometry}
        material={materials['Material.036']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube022_10.geometry}
        material={materials['Material.037']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cylinder011.geometry}
        material={materials['Material.006']}
      />
     
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cylinder011_1.geometry}
        material={materials['Material.007']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cylinder011_2.geometry}
        material={materials['Material.015']}
      />
      </RigidBody>
    </group>
        <Text rotation-y={THREE.MathUtils.degToRad(90)} position={[-249.1,17,130.1]} font="/text/JoeJack.ttf"scale={280}>
        Charging 
       </Text>
       <Text rotation-y={THREE.MathUtils.degToRad(90)} position={[-249.1,17,-170.1]} font="/text/JoeJack.ttf"scale={280}>
        Spot
       </Text>
  </>

 
   
  )
}

useGLTF.preload('/GasStation.glb')
